### ISSUE TITLE
How to require a lua moudle in a sandbox?

### ISSUE THREAD

**Issue by liuyangc3** [mozilla-services/lua_sandbox#111]
Hi, all

I write a lua sandbox
```
require "ltn12"
  ...
```

and when started hekad I got this error
```
2016/01/22 13:25:37 Error making runner for log4j_filter: Initialization failed for 'log4j_filter': Init() /usr/share/heka/nxin/log4j_filter.lua:3: module 'ltn12' not found:
        no file '/usr/share/heka/lua_modules/ltn12.lua'
        no file '/usr/share/heka/lua_modules/ltn12.so'
```
 but `require "cjson"` works fine

I find this moudle is in path `lua_io_modules`
```
# find /usr/share/heka/ -name ltn12.*
/usr/share/heka/lua_io_modules/ltn12.lua
```
I tried `require "lua_io_modules.ltn12"` and still not work
how can I require this muodle in a sandbox ?

**Comment by timurb** [comment]
Hi,

Haven’t tried to require custom lua module from heka but looking at your output I’d suggest to put your module to lua_modules dir instead of lua_io_modules.

Regards,
Timur

On 22 Jan 2016 at 08:59:02, web (notifications@github.com) wrote:

Hi, all

I write a lua sandbox

require "ltn12"


and when started hekad I got this error

2016/01/22 13:25:37 Error making runner for log4j_filter: Initialization failed for 'log4j_filter': Init() /usr/share/heka/nxin/log4j_filterlua:3: module 'ltn12' not found:
        no file '/usr/share/heka/lua_modules/ltn12lua'
        no file '/usr/share/heka/lua_modules/ltn12so'

but this moudle is in the path

# find /usr/share/heka/ -name ltn12*
/usr/share/heka/lua_io_modules/ltn12lua

I tried require "lua_io_modulesltn12" and still not work
how can I require this muodle in a sandbox ?

**Comment by trink** [comment]
For heka that module is only available for input or output sandboxes.  This is by design (since nothing else should be doing i/o).
