### ISSUE TITLE
Add support for decode_message to also return hash based message fields

### ISSUE THREAD

**Issue by bbinet** [mozilla-services/lua_sandbox#137]
Currently the `decode_message` function returns a message with "**Array Based** Message Fields" as described in https://github.com/mozilla-services/lua_sandbox/blob/master/docs/heka/message.md#array-based-message-fields

It would be great if `decode_message` could also return a message with "**Hash Based** Message Fields" as described in https://github.com/mozilla-services/lua_sandbox/blob/master/docs/heka/message.md#hash-based-message-fields
Most of the time, fields names are unique and the hash based format is then easier to use in the sandbox than the array based format.

We could for example add an optional boolean parameter to the `decode_message` function to decide on which fields format to use (the default value would keep the current array based format).

What do you think?

**Comment by trink** [comment]
I will update the sandbox docs with description and rationale from the Heka docs.

`message (table) The array based version of the message structure with the value member always being an array (even if there is only a single item). This format makes working with the output more consistent. The wide variation in the inject table format is to ease the construction of the message especially when using an LPeg grammar transformation.`

As for changing the decode_message functionality I would be a -1 since the array based representation is the actual representation and creating a 'convenience' representation that introduces complexity and edge cases is not a win for the library or end user.  Also, the transformation can be achieved with a small bit of Lua code, if desired.
